# Generated by Django 4.1.5 on 2023-02-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='otp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
